version: '3'
services:
  strapi:
    image: strapi/strapi:3
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2g


